### PR TITLE
Field improved

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
Allow specifying FIELD as range of columns.

### CODE REVIEW

**Comment by thierryvolpiatto** [comment]
Here a real example to use for bash history (add it to .bashrc):

```sh
ezfhistory () {
    if [ -n "$(command -v ezf)" ]; then
        COMMAND=$(history | ezf -f 1,)
        echo -n "> $COMMAND"
        read -r ANSWER
        if [ "$ANSWER" == "" ]; then
            eval "$COMMAND"
        else
            echo "Aborted"
        fi
    else
        echo "ezf is not installed"
    fi
    }
```

**Comment by mickeynp** [comment]
Looks cool, Thierry. I get an error when I use `ezfhistory` with escaped commands:

```
$ echo $(ls)
> echo \\$\\(ls\\)
bash: syntax error near unexpected token `('
```

Does that happen with your bash?

**Comment by thierryvolpiatto** [comment]
Hello Mickey,

Mickey Petersen ***@***.***> writes:

> Looks cool, Thierry. I get an error when I use ezfhistory with escaped commands:
>
> $ echo $(ls)
>> echo \\$\\(ls\\)
> bash: syntax error near unexpected token `('

Oops, forget to push last commits.

>
> Does that happen with your bash?

Yes with shell-quote-argument, should use identity instead.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by mickeynp** [comment]
Oh yeah now `ezfhistory` works, but I think the field logic is broken. `ezf` now defaults to the first word even if `-f` is `nil` (which is the default) or explicitly set to `0`.

**Comment by thierryvolpiatto** [comment]
Mickey Petersen ***@***.***> writes:

> Oh yeah now ezfhistory works, but I think the field logic is
> broken. ezf now defaults to the first word even if -f is nil (which is
> the default) or explicitly set to 0.

Thanks, will fix this ASAP (unless you beat me ;-)).

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Is this working for you (fully not tested):

```diff
diff --git a/ezf.el b/ezf.el
index 7d947d6..f2f3bc4 100644
--- a/ezf.el
+++ b/ezf.el
@@ -69,12 +69,13 @@
   "Regexp of separators `ezf' should use to split a line.")
 
 (defun ezf-1 (candidates &optional field)
-  (setq field
-        (if (and (stringp field) (string-match "," field))
-            (split-string field "," t)
-          (string-to-number field)))
+  (when field
+    (setq field
+          (if (and (stringp field) (string-match "," field))
+              (split-string field "," t)
+            (string-to-number field))))
   (mapconcat (lambda (candidate)
-               (cond ((numberp field)
+               (cond ((and (numberp field) (not (zerop field)))
                       ;; The field column of line.
                       (identity
                        (nth (1- field)
```

**Comment by thierryvolpiatto** [comment]
Also it would be better to index all from zero for consistency i.e. the -f integer value and the range:

```elisp
(ezf-1 '("1071 helmcd -nw") "1,")
;;=> "helmcd -nw"
(ezf-1 '("1071 helmcd -nw") "1")
;;=> "helmcd"
```

**Comment by thierryvolpiatto** [comment]
The patch then would be:

```diff
diff --git a/ezf.el b/ezf.el
index 7d947d6..cbef024 100644
--- a/ezf.el
+++ b/ezf.el
@@ -69,15 +69,16 @@
   "Regexp of separators `ezf' should use to split a line.")
 
 (defun ezf-1 (candidates &optional field)
-  (setq field
-        (if (and (stringp field) (string-match "," field))
-            (split-string field "," t)
-          (string-to-number field)))
+  (when field
+    (setq field
+          (if (and (stringp field) (string-match "," field))
+              (split-string field "," t)
+            (string-to-number field))))
   (mapconcat (lambda (candidate)
                (cond ((numberp field)
                       ;; The field column of line.
                       (identity
-                       (nth (1- field)
+                       (nth field
                             (split-string candidate ezf-separators t " "))))
                      ((consp field)
                       (let* ((beg (string-to-number (car field)))

```

**Comment by thierryvolpiatto** [comment]
Here the tests (should be reordered):

```elisp
(ert-deftest test-ezf-1 ()
  (let ((test1 (ezf-1 '("autodep8 - générateur de fichiers de contrôle de test DEP-8") "0"))
        (test2 (ezf-1 '("autodep8 - générateur de fichiers de contrôle de test DEP-8") "1"))
        (test3 (ezf-1 '("autodep8 - générateur de fichiers de contrôle de test DEP-8") "2"))
        (test4 (ezf-1 '("autodep8 - générateur de fichiers de contrôle de test DEP-8") "2,4"))
        (test5 (ezf-1 '("1071 helmcd -nw") "1,"))
        (test6 (ezf-1 '("1071 helmcd -nw") "1,2"))
        (test7 (ezf-1 '("1071 helmcd -nw") "2"))
        (test8 (ezf-1 '("1071 helmcd -nw") "0,"))
        (test9 (ezf-1 '("1071 helmcd -nw") "0"))
        (test10 (ezf-1 '("1071 helmcd -nw") "1"))
        (test11 (ezf-1 '("1071 helmcd -nw") "2")))
    (should (string= test1 "autodep8"))
    (should (string= test2 "-"))
    (should (string= test3 "générateur"))
    (should (string= test4 "générateur de fichiers"))
    (should (string= test5 "helmcd -nw"))
    (should (string= test6 "helmcd -nw"))
    (should (string= test7 "-nw"))
    (should (string= test8 "1071 helmcd -nw"))
    (should (string= test9 "1071"))
    (should (string= test10 "helmcd"))
    (should (string= test11 "-nw"))))
```

**Comment by mickeynp** [comment]
Looks good, but I'll change `,` to `-` to keep it consistent with range specifiers in tools like `cut` etc.

**Comment by mickeynp** [comment]
Thanks for the help, Thierry!

**Comment by thierryvolpiatto** [comment]
Mickey Petersen ***@***.***> writes:

> Looks good, but I'll change , to - to keep it consistent with range
> specifiers in tools like cut etc.

Yes! Good catch.
Thanks.

>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.*Message ID: ***@***.***>


-- 
Thierry

**Pull request merged**
